version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8876:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: testclrf_nginx
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    container_name: testclrf_php

  #node:
  #  build:
  #    dockerfile: ./docker/node/Dockerfile
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - ./:/var/www
  #  depends_on:
  #    - php
  #  container_name: testclrf_node

  db:
    image: mariadb:10.11
    restart: always
    ports:
      - 8101:3306
    volumes:
      - ./tmp/db/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test-clrf
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: testclrf_db


